sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t proreef/test04 -f Dockerfile.dev .

script:
  - docker run -e CI=true proreef/test04 npm run test -- --coverage

after_success:
  - echo "Test Success"